version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  allow:
    - dependency-name: "*"
      dependency-type: "production"
  schedule:
    interval: weekly
    day: saturday
    time: '07:00'
    timezone: Asia/Yerevan
  open-pull-requests-limit: 10
  assignees:
  - l5x
  versioning-strategy: increase
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
