on:
  workflow_call:
    outputs:
      value:
        description: "pnpm version"
        value: ${{ jobs.main.outputs.value }}
jobs:
  main:
    runs-on: ubuntu-latest
    outputs:
      value: ${{ steps.pnpm_version.outputs.value }}
    steps:
      - uses: actions/checkout@v3
      - name: get pnpm version
        id: pnpm_version
        run: |
          echo "::set-output name=value::$(cat package.json | jq -r .engines.pnpm | grep -oP '([0-9]+)\.([0-9]+)\.([0-9]+)' | head -n 1)"
